qc:
  adapter1: AGATCGGAAGAGCGGTTCAGCAGGAATGCCGAGACCGATCTCGTATGCCGTCTTCTGCTTG
  adapter2: AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGTAGATCTCGGTGGTCGCCGTATCATT

mapping:
  aligners:
    - ngm
      #    - bwa
  refs:
    - bdisv3

refs:
  bdisv3: rawdata/references/Bdis_v3/Bdistachyon_314_v3.0.fa

varcall:
  chunksize: 1000000
  aligners:
    - ngm
  # - bwa
  callers:
  #  - freebayes
    - mpileup
  refs:
    - bdisv3
  

lanes:
  brachy_01:
    combo: false
  brachy_02:
    combo: false
  brachy_03:
    combo: false
  brachy_04:
    combo: false
  brachy_05:
    combo: true
  brachy_06:
    combo: false
  brachy_09-10:
    combo: true
  brachy_11-14:
    combo: true
  brachy_15-20:
    combo: true
  brachy_27-32:
    combo: true
