qc:
  adapter1: AGATCGGAAGAGCGGTTCAGCAGGAATGCCGAGACCGATCTCGTATGCCGTCTTCTGCTTG
  adapter2: AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGTAGATCTCGGTGGTCGCCGTATCATT
  minqual: 20

minreads: 1000

refs:
  bdisv3: rawdata/references/Bdistachyon/assembly/Bdistachyon_314_v3.0.fa
  bd21-3: rawdata/references/BdistachyonBd21_3_460_v1.1/assembly/BdistachyonBd21_3_460_v1.0.fa
  bhybridum: rawdata/references/Bhybridum-pseudogenome/Bhybridum.fa


mapping:
  aligners:
    #- ngm
    - bwa
  refs:
    - bdisv3
    - bd21-3
    - bhybridum

varcall:
  samplesets:
    #- GBS-all
    - GBS-distachyon
    - WGS-all
  chunksize: 1000000
  aligners:
    - bwa
  callers:
    - freebayes
    - mpileup
  refs:
    - bd21-3
      #- bhybridum
  filters:
    default: >
      -i 'QUAL >= 10 &&
          ALT != "." &&
          INFO/DP >= 5 &&
          INDEL=0 &&
          INFO/AN >= 3'
#    strict: >
#      -i 'INFO/MQ >= 30 &&
#          QUAL >= 40 &&
#          ALT != "." &&
#          INFO/DP >= 10 &&
#          INDEL=0 &&
#          ((INFO/AN / N_SAMPLES)*2) > 0.50'

lanes:
  brachy_01:
    combo: false
  brachy_02:
    combo: false
  brachy_03:
    combo: false
  brachy_04:
    combo: false
#  brachy_05:
#    combo: true
  brachy_06:
    combo: false
  brachy_09-10:
    combo: true
  brachy_11-14:
    combo: true
  brachy_15-20:
    combo: true
  brachy_16-17:
    combo: true
  brachy_27-32:
    combo: true
